package pe.com.dentalamericana.admin;
import jakarta.servlet.http.HttpServletRequest;import org.springframework.data.domain.*;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;import pe.com.dentalamericana.admin.dto.AdminDtos.*;import pe.com.dentalamericana.appointment.*;import pe.com.dentalamericana.audit.*;import pe.com.dentalamericana.clinical.*;import pe.com.dentalamericana.common.*;import pe.com.dentalamericana.finance.*;import pe.com.dentalamericana.finance.dto.FinanceDtos.FinanceDashboard;import pe.com.dentalamericana.messaging.*;import pe.com.dentalamericana.patient.*;import pe.com.dentalamericana.security.AuthenticatedUser;import pe.com.dentalamericana.user.*;import java.time.*;import java.util.List;
@Service public class AdministrationService{private final SystemSettingRepository settings;private final AuditLogRepository audits;private final PatientRepository patients;private final AppointmentRepository appointments;private final ClinicalEncounterRepository encounters;private final FinanceService finance;private final PostConsultationFollowUpRepository followups;private final WhatsAppMessageRepository messages;private final AuditService audit;private final AppUserRepository users;public AdministrationService(SystemSettingRepository settings,AuditLogRepository audits,PatientRepository patients,AppointmentRepository appointments,ClinicalEncounterRepository encounters,FinanceService finance,PostConsultationFollowUpRepository followups,WhatsAppMessageRepository messages,AuditService audit,AppUserRepository users){this.settings=settings;this.audits=audits;this.patients=patients;this.appointments=appointments;this.encounters=encounters;this.finance=finance;this.followups=followups;this.messages=messages;this.audit=audit;this.users=users;}
@Transactional(readOnly=true)public List<SettingResponse>settings(){return settings.findAllByOrderByClaveAsc().stream().map(this::setting).toList();}
@Transactional public SettingResponse update(String key,UpdateSettingRequest r,AuthenticatedUser actor,HttpServletRequest http){SystemSetting s=settings.findById(key).orElseThrow(()->new ResourceNotFoundException("Configuración no encontrada"));if(!s.getVersion().equals(r.version()))throw new BusinessConflictException("La configuración fue modificada por otro usuario");s.update(r.value().trim(),actor.getId());record(actor,"ACTUALIZAR_CONFIGURACION",key,"Parámetro actualizado",http);return setting(s);}
@Transactional(readOnly=true)public Page<AuditResponse>audits(Instant from,Instant to,String query,int page,int size){range(from,to,366);Pageable pageable=PageRequest.of(Math.max(0,page),Math.min(Math.max(size,1),100));String q=query==null||query.isBlank()?null:query.trim();return (q==null?audits.searchAll(from,to,pageable):audits.search(from,to,q,pageable)).map(this::audit);}
@Transactional(readOnly=true)public OperationalSummary summary(Instant from,Instant to){range(from,to,366);FinanceDashboard f=finance.dashboard(from,to);return new OperationalSummary(patients.count(),appointments.countByInicioBetween(from,to),appointments.countByInicioBetweenAndEstado(from,to,AppointmentStatus.CONFIRMADA),encounters.countByEncounterDateBetweenAndEstado(from,to,ClinicalStatus.FINALIZADA),f.income(),f.expenses(),f.net(),f.receivable(),followups.countByEstado(FollowUpStatus.ALERTA),messages.countByEstadoAndCreatedAtBetween(MessageStatus.FALLIDO,from,to),from,to);}
@Transactional(readOnly=true)public String csv(Instant from,Instant to){OperationalSummary s=summary(from,to);return "REPORTE OPERATIVO Y FINANCIERO - DENTAL AMERICANA\nDesde,"+from+"\nHasta,"+to+"\n\nIndicador,Valor\nPacientes registrados,"+s.patients()+"\nCitas del periodo,"+s.appointments()+"\nCitas confirmadas,"+s.confirmedAppointments()+"\nAtenciones finalizadas,"+s.completedEncounters()+"\nIngresos,"+s.income()+"\nGastos,"+s.expenses()+"\nResultado,"+s.net()+"\nCuentas por cobrar,"+s.receivables()+"\nAlertas de seguimiento,"+s.followUpAlerts()+"\nMensajes fallidos,"+s.failedMessages()+"\n\nNota,Reporte administrativo sujeto a validación contable y tributaria.\n";}
private SettingResponse setting(SystemSetting s){return new SettingResponse(s.getKey(),s.getValue(),s.getDescription(),s.getUpdatedBy(),s.getUpdatedAt(),s.getVersion());}private AuditResponse audit(AuditLog a){return new AuditResponse(a.getId(),a.getUserId(),a.getUsername(),a.getAction(),a.getResource(),a.getResourceId(),a.getResult(),a.getIp(),a.getDetail(),a.getCreatedAt());}private void range(Instant f,Instant t,long days){if(f==null||t==null||!t.isAfter(f)||Duration.between(f,t).toDays()>days)throw new BusinessConflictException("Rango de consulta inválido");}private void record(AuthenticatedUser a,String action,String id,String detail,HttpServletRequest h){AppUser u=users.findById(a.getId()).orElse(null);audit.record(u,action,"CONFIGURACION",id,AuditResult.EXITO,detail,h);}}
