app:
  bootstrap-admin:
    enabled: true
    username: ${APP_ADMIN_USERNAME:admin}
    password: ${APP_ADMIN_PASSWORD:Cambiar123!}
    full-name: ${APP_ADMIN_FULL_NAME:Administrador Dental Americana}

spring:
  flyway:
    locations: classpath:db/migration,classpath:db/demo
